version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   - MONGODB_USERNAME=Andrew
    #   - MONGODB_PASSWORD=secret
    #   MONGODB_PASSWORD: secret
    env_file:
      - ./env/mongo.env
  backend:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile-dev
    #   args:
    #     some-arg: 1
    build: ./backend/
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend/
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
