apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-backend
  template:
    metadata:
      labels:
        app: story-backend
    spec:
      containers:
        - name: story-nodejs
          image: xianchengz/kube_data_example_stories
          # env:
          #   - name: STORY_FOLDER
          #     value: 'story'
          # alternatively use config map
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
