apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: xianchengz/kube-demo-users:3
          env:
            - name: AUTH_ADDRESS
              value: 'auth-service.default'
            - name: PORT
              value: '5000'
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
